# Generated by Django 4.2 on 2024-03-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='alpha',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Alpha (α)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='beta',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Beta (β)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='lower_bound',
            field=models.IntegerField(verbose_name='Lower Bound (a)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='std_dev_demand_lead_time',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Standard Deviation of Demand During Lead Time (σd)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='upper_bound',
            field=models.IntegerField(verbose_name='Upper Bound (b)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], max_length=50, verbose_name='Stock Level'),
        ),
    ]
