# Generated by Django 4.2 on 2024-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_continuousreviewrqpolicy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousreviewrqpolicy',
            name='abbr',
            field=models.CharField(default='R, Q', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='continuousreviewsspolicy',
            name='abbr',
            field=models.CharField(default='s, S', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='periodicreviewtspolicy',
            name='abbr',
            field=models.CharField(default='T, S', editable=False, max_length=100),
        ),
    ]
