# Generated by Django 4.2 on 2024-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_continuousreviewrqpolicy_abbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_level',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
