# Generated by Django 4.2 on 2024-03-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousreviewsspolicy',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity (Q)'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Awaiting', 'Awaiting'), ('Completed', 'Completed')], default='Awaiting', max_length=15)),
                ('estimated_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
