# Generated by Django 4.2 on 2024-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_continuousreviewsspolicy_order_quantity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='desired_service_level',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='distribution_type',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='gamma_distribution_data',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='lower_bound',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='mean_demand_rate',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='std_dev_daily_demand',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='std_dev_demand_lead_time',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='upper_bound',
        ),
        migrations.AddField(
            model_name='continuousreviewrqpolicy',
            name='beta_distribution_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continuousreviewrqpolicy',
            name='gamma_distribution_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continuousreviewrqpolicy',
            name='normal_distribution_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continuousreviewrqpolicy',
            name='uniform_distribution_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='average_demand',
            field=models.IntegerField(verbose_name='Average Demand (µd)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='eoq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Economic Order Quantity (EOQ)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='holding_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Holding Cost (H)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='number_of_days_in_year',
            field=models.IntegerField(verbose_name='Number of Days in Year (D)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='order_lead_time',
            field=models.IntegerField(verbose_name='Order Lead Time (LT)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='reorder_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reorder Point (ROP)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='setup_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Setup Cost (S)'),
        ),
    ]
