# Generated by Django 4.2 on 2024-03-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_continuousreviewrqpolicy_alpha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distribution',
            field=models.CharField(blank=True, choices=[('Normal Distribution', 'Normal Distribution'), ('Uniform Distribution', 'Uniform Distribution'), ('Beta Distribution', 'Beta Distribution'), ('Gamma Distribution', 'Gamma Distribution')], max_length=50, null=True, verbose_name='Distribution'),
        ),
    ]
