# Generated by Django 4.2 on 2024-03-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_continuousreviewrqpolicy_is_constant_demand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='policy_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
