# Generated by Django 4.2 on 2024-03-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_policy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Low', 'Low')], max_length=50, verbose_name='Stock Level'),
        ),
        migrations.CreateModel(
            name='InvetorylevelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('is_stockout', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
