# Generated by Django 4.2 on 2024-03-23 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_stock_level_invetorylevelupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invetorylevelupdate',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
