# Generated by Django 4.2 on 2024-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Awaiting', 'Awaiting'), ('Completed', 'Completed')], default='Awaiting', max_length=15, null=True),
        ),
    ]
