# Generated by Django 4.2 on 2024-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_notification_product_notification_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='average_lead_time',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='holding_cost',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='number_of_days_in_year',
        ),
        migrations.RemoveField(
            model_name='continuousreviewrqpolicy',
            name='setup_cost',
        ),
        migrations.AlterField(
            model_name='continuousreviewrqpolicy',
            name='eoq',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity'),
        ),
        migrations.AlterField(
            model_name='continuousreviewsspolicy',
            name='maximum_stock_level',
            field=models.IntegerField(verbose_name='Maximum Stock Level (S)'),
        ),
        migrations.AlterField(
            model_name='continuousreviewsspolicy',
            name='minimum_stock_level',
            field=models.IntegerField(verbose_name='Minimum Stock Level (s)'),
        ),
    ]
